- composer.json
- inc/class-command.php
- inc/class-commandprovider.php
- inc/class-composerplugin.php
This adds `composer chassis init`, and friends: `start`, `status`, `stop`.
> Add first pass at Chassis commands

- inc/class-command.php
> Switch to meta-extension

- inc/class-command.php
This is required by ElasticPress.
Thinking this should go in 1.0.1?
> Add ingest-attachment plugin

- inc/class-command.php
> Fix PHP version to 7.2

- load.php
> Fix compatibility with Chassis hosts plugin

- docs/README.md
- inc/class-command.php
> Add shell helper command

- docs/README.md
- inc/class-command.php
Blocked by 
Fixes #17
This needs some testing still, in particular on Windows.
> Add command to install cert generated by openssl extension

- docs/README.md
- inc/class-command.php
> Allow setting hosts in the config

- inc/class-command.php
> Set machine name from host

- README.md
- docs/README.md
Changes docs content from BE to AE.
> Docs: BE → AE

- composer.json
- inc/class-command.php
- inc/class-commandprovider.php
- inc/class-composerplugin.php
- inc/namespace.php
- load.php
Maps Query Monitor paths in Chassis on to their host filesystem equivalents
> map qm paths on to chassis synced folders

- docs/README.md
- inc/class-command.php
Upgrade chassis and the extensions then re provisions the machine.
> Add upgrade command

- inc/class-command.php
> Add notice to file that it is managed by chassis

- inc/class-command.php
> Allow overriding default host

- inc/class-command.php
This ratifies the two local environments and their commands to `local-chassis / chassis` and `local-server / server``
> Add local-chassis alias

- inc/class-command.php
> #40 Add user/pass/admin url on successful start

- inc/class-command.php
> #44: init command exits if any step's exit code is not 0

- inc/class-command.php
This brings local chassis in line with production and local server.
> Use ElasticSearch version 6.3.1

- inc/class-command.php
@roborourke I am completely new to Altis and I am not sure this is the desired git workflow and generally way of doing things here, please advice if something needs to be changed.
> Adding ssh command, per issue-70

- docs/README.md
- inc/class-command.php
> Adding destroy command

- inc/namespace.php
Related to user dictionary support https://github.com/humanmade/altis-enhanced-search/pull/76
> Add support for ES packages

- composer.json
- inc/class-composerplugin.php
> [Backport v3-branch] Add Composer v2 support

- inc/class-command.php
> [Backport v4-branch] Update class-command.php

- inc/class-command.php
> [Backport v5-branch] Update class-command.php

- inc/class-command.php
Sets the default PHP version to 7.4. Fixes #113
> Update to PHP 7.4

- docs/README.md
- inc/class-command.php
> Change back to PHP 7.2 and document 7.4 upgrade

- composer.json
5.4 breaks compatibility with PHP < 8.1
> require patch releases of symfony/yaml 5.3 only

- inc/namespace.php
> Set HTTP_HOST if empty from config

- docs/README.md
- inc/class-command.php
This is blocked by https://github.com/Chassis/Chassis_Elasticsearch/pull/31
Fixes https://github.com/humanmade/product-dev/issues/765
> Update default ES version to 7.10

- inc/class-command.php
> Update the broken link
